apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: propati
resources:
  - service.yaml
  - deployment.yaml
#  - ingress.yaml

commonLabels:
  app: propati-api

commonAnnotations:
  app: propati-api

namePrefix:
  fusesl-

nameSuffix:
  -v1