#name: Kubernetes Deploy
#
#on:
#  push:
#    branches:
#      - dev
#
#jobs:
#  deploy:
#    runs-on: "self-hosted"
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      # test micro status
#      - name: Test Minikube Status commands
#        id: minikube
#        run: |
#          set -ex
#          echo "Executing minikube status command."
#          minikube status
#
#      # login to docker
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      # build from the dockerfile in the default directory and push to docker hub
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          docker_compose: 'docker-compose.yaml'
#          tags: fusesl/propati-api:latest
#
#      # Run the kustomize file to create/update the deployments/servicess
#      - name: Run the kustomize files
#        run: kubectl apply -k k8s/overlays/dev
#
